# Generated by Django 3.1.3 on 2021-01-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210108_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='catgories',
            field=models.ManyToManyField(default=1, to='posts.Category'),
        ),
    ]
