# Generated by Django 3.1.3 on 2021-01-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210108_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='region',
            field=models.CharField(default='', max_length=30),
        ),
    ]
