# Generated by Django 3.1.3 on 2021-01-08 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210108_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='catgories',
            new_name='categories',
        ),
    ]
