# Generated by Django 3.1.3 on 2021-01-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
