# Generated by Django 3.1.3 on 2021-01-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20210113_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='city',
        ),
        migrations.RemoveField(
            model_name='post',
            name='price',
        ),
        migrations.RemoveField(
            model_name='post',
            name='region',
        ),
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
